// This file was auto-generated by @joelek/ts-autoguard. Edit at own risk.

import { Playlist } from "./schema";
import { PlaylistItem } from "./schema";
import { guards as autoguard } from "@joelek/ts-autoguard";

export type SetToken = {
	"token"?: string
};

export const SetToken = autoguard.Object.of<SetToken>({
	"token": autoguard.Union.of(
		autoguard.Undefined,
		autoguard.String
	)
});

export type PlaylistRequest = string;

export const PlaylistRequest = autoguard.String;

export type PlaylistResponse = Playlist;

export const PlaylistResponse = autoguard.Reference.of<Playlist>(() => Playlist);

export type PlaylistInvalidate = string;

export const PlaylistInvalidate = autoguard.String;

export type PlaylistItemRequest = string;

export const PlaylistItemRequest = autoguard.String;

export type PlaylistItemResponse = PlaylistItem;

export const PlaylistItemResponse = autoguard.Reference.of<PlaylistItem>(() => PlaylistItem);

export type PlaylistItemInvalidate = string;

export const PlaylistItemInvalidate = autoguard.String;

export type Batch = {
	"playlists": Playlist[],
	"playlist_items": PlaylistItem[]
};

export const Batch = autoguard.Object.of<Batch>({
	"playlists": autoguard.Array.of(autoguard.Reference.of<Playlist>(() => Playlist)),
	"playlist_items": autoguard.Array.of(autoguard.Reference.of<PlaylistItem>(() => PlaylistItem))
});

export type Autoguard = {
	"SetToken": SetToken,
	"PlaylistRequest": PlaylistRequest,
	"PlaylistResponse": PlaylistResponse,
	"PlaylistInvalidate": PlaylistInvalidate,
	"PlaylistItemRequest": PlaylistItemRequest,
	"PlaylistItemResponse": PlaylistItemResponse,
	"PlaylistItemInvalidate": PlaylistItemInvalidate,
	"Batch": Batch
};

export const Autoguard = {
	"SetToken": SetToken,
	"PlaylistRequest": PlaylistRequest,
	"PlaylistResponse": PlaylistResponse,
	"PlaylistInvalidate": PlaylistInvalidate,
	"PlaylistItemRequest": PlaylistItemRequest,
	"PlaylistItemResponse": PlaylistItemResponse,
	"PlaylistItemInvalidate": PlaylistItemInvalidate,
	"Batch": Batch
};
